In [2]:
import numpy as np

Problem - 1:

Array Creation:

Complete the following Tasks:

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

1.

In [19]:
a = np.empty((2,2))
print(a)

[[4.78561632e-310 0.00000000e+000]
 [4.78678401e-310 6.90731340e-310]]


2.

In [7]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3.

In [34]:
a = np.full((2,2),5)
print(a)

[[5 5]
 [5 5]]


4.

In [35]:
a = np.zeros_like(a)
print(a)

[[0 0]
 [0 0]]


5.

In [10]:
a = np.ones_like(a)
a

array([[1, 1],
       [1, 1]])

6.

In [11]:
a = [1,2,3,4]
a = np.array(a)
a

array([1, 2, 3, 4])

Problem - 2:

Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

1.

In [10]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.

In [14]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3.

In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.

In [16]:
a = np.random.random(30)
a.mean()

0.531549429715963

5.

In [21]:
a = np.random.random((10, 10))
min_value = a.min()
max_value = a.max()
print("min value:", min_value)
print("max value:", max_value)

min value: 0.016313422905266384
max value: 0.9895718554144559


6.

In [15]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.

In [16]:
a = np.array([1,2,0,0,4,0])
a = a[::-1]
print(a)

[0 4 0 0 2 1]


8.

In [17]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9.

In [18]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3:

Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [32]:
import numpy as np

# Arrays
a = np.array([[1, 2], [3, 5]])
b = np.array([[5, 6], [7, 8]])
c = np.array([9, 10])
d = np.array([11, 12])

#1.

a = a + b
print(a)




#2.

a = a - b
print(a)



#3.

a = a * 2
print(a)



#4.

a = np.square(a)
print(a)




#5.

#Dot product of c (v) and d (w)
a = np.dot(c, d)
print(a)

#Dot product of a (x) and c (v)
a = np.dot(a, c)
print(a)

#Dot product of a (x) and b (y)
a = np.dot(a, b)
print(a)



#6
a = np.vstack((c, d))


#7.
try:
    a = np.concatenate((a, c), axis=0)
    print("\nConcatenation of a (x) and c (v):\n", a)
except ValueError as e:
    print("\nError during concatenation of a (x) and c (v):")
    print(e)
    print("Explanation: `a` (x) is a 2D array (2x2), but `c` (v) is a 1D array (1x2). Their dimensions do not align for concatenation.")


[[ 6  8]
 [10 13]]
[[1 2]
 [3 5]]
[[ 2  4]
 [ 6 10]]
[[  4  16]
 [ 36 100]]
219
[1971 2190]
[25185 29346]

Error during concatenation of a (x) and c (v):
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: `a` (x) is a 2D array (2x2), but `c` (v) is a 1D array (1x2). Their dimensions do not align for concatenation.


Problem - 4:

Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [33]:
import numpy as np

# Given arrays (matrices A and B)
a = np.array([[3, 4], [7, 8]])
b = np.array([[5, 3], [2, 1]])

# 1. Prove a * a^-1 = I
a_inv = np.linalg.inv(a)
i = np.dot(a, a_inv)
print("a * a^-1 = I (Identity Matrix):\n", i)

# 2. Prove a * b != b * a
ab = np.dot(a, b)
ba = np.dot(b, a)
print("\na * b (a * b):\n", ab)
print("\nb * a (b * a):\n", ba)
print("\na * b == b * a? ", np.array_equal(ab, ba))

# 3. Prove (a * b)^T = b^T * a^T
ab_T = np.transpose(ab)
b_T_a_T = np.dot(np.transpose(b), np.transpose(a))
print("\n(a * b)^T:\n", ab_T)
print("\nb^T * a^T:\n", b_T_a_T)
print("\n(a * b)^T == b^T * a^T? ", np.array_equal(ab_T, b_T_a_T))

# 4. Solve the system of linear equations using Inverse Method (aX = b)
# Coefficients matrix a
a_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

# Right-hand side matrix b
b_matrix = np.array([-1, -3, 9])

# Solve for X using the inverse method: X = a_inv * b
a_inv_matrix = np.linalg.inv(a_matrix)  # Inverse of a_matrix
x = np.dot(a_inv_matrix, b_matrix)  # Solve for X
print("\nSolution to the system of equations (X):\n", x)


a * a^-1 = I (Identity Matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

a * b (a * b):
 [[23 13]
 [51 29]]

b * a (b * a):
 [[36 44]
 [13 16]]

a * b == b * a?  False

(a * b)^T:
 [[23 51]
 [13 29]]

b^T * a^T:
 [[23 51]
 [13 29]]

(a * b)^T == b^T * a^T?  True

Solution to the system of equations (X):
 [ 2.  1. -2.]
